name: Generate Ascii Artwork

on: push

jobs: 
    ascii_job:
        runs-on: ubuntu-latest
        steps: 
        - name: Checkout Repo
          uses: actions/checkout@v4
        
        - name: Install Cowsay
          run: |
            sudo apt-get install cowsay -y
          
        - name: Generate ASCII ArtWork
          run: cowsay -f dragon "Run For Cover, I am a LION ....... " > dragon.txt

        - name: Test File Exists
          run: grep -i "dragon" dragon.txt 

        - name: Read Files
          run: cat dragon.txt           
          
        - name: Checkout Repo Files
          run: ls -ltra         