name: Generate Ascii Artwork

on: push

jobs: 
    build_job1:
        runs-on: ubuntu-latest
        steps: 
        - name: Checkout Repo
          uses: actions/checkout@v4
        
        - name: Install Cowsay
          run: |
            sudo apt-get install cowsay -y
          
        - name: Generate ASCII ArtWork
          run: cowsay -f dragon "Run For Cover, I am a LION ....... " > dragon.txt

        - name: Upload Dragon File
          uses: actions/upload-artifact@v4
          with:
            name: dragon-file
            path: dragon.txt
                 
    test_job2:
        needs: build_job1
        runs-on: ubuntu-latest
        steps:             
        - name: Download Dragon File
          uses: actions/download-artifact@v4
          with:
            name: dragon-file
              
        - name: Generate ASCII ArtWork
          run: ls dragon.txt              

    deploy_job3:
        needs: [build_job1,test_job2]
        runs-on: ubuntu-latest
        steps: 
        - name: Download Dragon File
          uses: actions/download-artifact@v4
          with:
            name: dragon-file
                
        - name: Read Files
          run: cat dragon.txt           
          
        - name: Deploy
          run: echo Deloying.......                      